name: Create a release PR

on:
  push:
    branches:
      - release
jobs:
  createReleasePR:
    name: createReleasePR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: yarn install
        run: yarn
      - name: configure release bot
        run: git config user.email "bot@simsala.de" && git config user.name "Simsala Release Bot"
      - name: create release PR
        run: yarn start release-candidate --semver patch --token ${{ secrets.GIT_BOT_TOKEN }} -b origin/master
